# Site settings
title: Michael's SFPC Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    This blog will document my time at the SFPC during Fall 2015.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mgs.github.io" # the base hostname & protocol for your site
twitter_username: ArtfulDeleuzian
github_username:  mgs

# Build settings
markdown: kramdown
